/* Scalar functions */
SELECT UPPER(LASTNAME) || ', ' || UPPER(FIRSTNAME) AS CUSTOMER_INFO
FROM CUSTOMER
ORDER BY CUSTOMER_INFO;

/* Aggregate functions */
SELECT CUSTOMERID, TOTAL FROM INVOICE ORDER BY CUSTOMERID;

SELECT CUSTOMERID, ROUND(AVG(TOTAL),2) AS AVG_TOTAL FROM INVOICE GROUP BY CUSTOMERID ORDER BY CUSTOMERID;

/* Having */
SELECT CUSTOMERID, COUNT(CUSTOMERID) AS PURCHASES 
FROM INVOICE 
GROUP BY CUSTOMERID 
HAVING COUNT(CUSTOMERID) > 6
ORDER BY CUSTOMERID;

/* Sub queries example */
SELECT FIRSTNAME FROM CUSTOMER WHERE CUSTOMERID IN 
(SELECT CUSTOMERID FROM INVOICE WHERE TOTAL > 16.0);

/* Join example */
SELECT 
C.LASTNAME || ', ' || C.FIRSTNAME AS CUSTOMER_INFO,
ROUND(AVG(I.TOTAL),2) AS AVERAGE_PURCHASES
FROM CUSTOMER C INNER JOIN INVOICE I
ON C.CUSTOMERID = I.CUSTOMERID
GROUP BY(C.LASTNAME,C.FIRSTNAME)
ORDER BY CUSTOMER_INFO;

/* Set */
SELECT FIRSTNAME FROM EMPLOYEE
INTERSECT
SELECT FIRSTNAME FROM CUSTOMER ORDER BY FIRSTNAME;
