#this is a comment in yml

server:
  port: 9030
  

spring:
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_URL}/foodDB
    password: ${TRAINING_DB_PASSWORD}
    username: datachan
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
      
      
      
#inside of a proteries file you'd have to do this:
# spring.datasource.url = ...stuff
# spring.datasource.username= ...stuff
# spring.datasource.password= ...stuff
# and so on.....
  
  
  
  
  
  
  
  