package com.revature.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-15T16:21:06.931-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "jediGreetingService", 
                  wsdlLocation = "http://10.226.49.70:8080/SOAPService/jediGreeting?wsdl",
                  targetNamespace = "http://soap.revature.com/") 
public class JediGreetingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.revature.com/", "jediGreetingService");
    public final static QName JediGreetingForcePort = new QName("http://soap.revature.com/", "JediGreetingForcePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.226.49.70:8080/SOAPService/jediGreeting?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JediGreetingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.226.49.70:8080/SOAPService/jediGreeting?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JediGreetingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JediGreetingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JediGreetingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JediGreetingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JediGreetingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JediGreetingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JediGreeting
     */
    @WebEndpoint(name = "JediGreetingForcePort")
    public JediGreeting getJediGreetingForcePort() {
        return super.getPort(JediGreetingForcePort, JediGreeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JediGreeting
     */
    @WebEndpoint(name = "JediGreetingForcePort")
    public JediGreeting getJediGreetingForcePort(WebServiceFeature... features) {
        return super.getPort(JediGreetingForcePort, JediGreeting.class, features);
    }

}
