package com.revature.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-15T16:21:06.923-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soap.revature.com/", name = "JediGreeting")
@XmlSeeAlso({ObjectFactory.class})
public interface JediGreeting {

    @WebMethod
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://soap.revature.com/", className = "com.revature.soap.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://soap.revature.com/", className = "com.revature.soap.GetMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
